services:
  - type: web
    name: dhikr-tahajjud-bot
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROUP_CHAT_ID
        sync: false
      - key: BD_TZ
        value: Asia/Dhaka
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_API_KEY
        sync: false
      - key: HADITH_API_KEY
        sync: false
      - key: ADMIN_PIN
        value: "7860"
      - key: WEB_APP_URL
        sync: false
